vetherasset/vaderprotocol-contracts

README.md

Resolve Issue12: Solc0.8

---

contracts/USDV.sol

Resolve: Issue30

---

test/9_synths.js

Resolve SYNTHS (extra tests)

---

.github/workflows/build.yml

Example run can be seen here: https://github.com/0xCubed/vaderprotocol-contracts/runs/2391698575

Add Initial CI Checks for Pushes/PR's Against Main

---

contracts/Synth.sol

declare some state variables as immutable. This will save gas

Synth immutable variables

---

contracts/Pools.sol

pool: cache synth address

---

contracts/Router.sol

Router: constants

---

contracts/DAO.sol
contracts/Synth.sol
contracts/Token1.sol
contracts/Token2.sol
contracts/USDV.sol
contracts/Utils.sol
contracts/Vader.sol
contracts/Vault.sol
contracts/Vether.sol

Hopefully this takes care of most of the low-hanging `constant` fruit (issue filter `label:"G (Gas Optimization)" constant`).
After this, slither reports nothing with its `constable-states` detector.
I think we could make some additional stuff `immutable` if we move initialization into the constructor rather than `init()`.  Please advise.

Gas optimization constants

---

contracts/USDV.sol

USDV: emit Transfer even if amount is zero

---

contracts/Attack.sol
contracts/DAO.sol
contracts/Factory.sol
contracts/Pools.sol
contracts/Router.sol
contracts/Synth.sol
contracts/Token1.sol
contracts/Token2.sol
contracts/USDV.sol
contracts/Utils.sol
contracts/Vader.sol
contracts/Vault.sol
contracts/Vether.sol

After this, `*.sol` is clean with regard to slither's `external-function` detector.

make public functions external if not called by contract

---

contracts/Vader.sol

fixes
https://github.com/vetherasset/vaderprotocol-contracts/issues/124

vader: disable redeem if not minting

---

contracts/USDV.sol

fixes
https://github.com/vetherasset/vaderprotocol-contracts/issues/123

usdv: disable convert if Vader not minting

---

contracts/DAO.sol

update isEqual visibility to internal from public since it's only used in DAO.sol

update isEqual visibility to internal from public since it's only used in DAO.sol

---

contracts/Router.sol

Resolve Issue165

---

README.md
contracts/Factory.sol
contracts/Pools.sol
contracts/Reserve.sol
contracts/Router.sol
contracts/USDV.sol
contracts/Utils.sol
contracts/Vault.sol
test/10_lend.js
test/11_interest.js
test/1_vader.js
test/2_usdv.js
test/3_router.js
test/4_protection.js
test/5_rewards.js
test/6_anchor.js
test/7_dao.js
test/8_curation.js
test/9_synths.js

Resolve Issue132

---

contracts/Pools.sol
contracts/Router.sol
contracts/interfaces/iPOOLS.sol

Resolve Issue 204

---

contracts/Router.sol

Resolve Issue 200: synth checks

---

contracts/Pools.sol
contracts/Router.sol
contracts/Vault.sol
contracts/interfaces/iPOOLS.sol
test/9_synths.js

Issue 196 new approach

---

contracts/Factory.sol
contracts/Synth.sol

For deploy, new Synth(token) seems to not work correctly.

Factory issynth fixing bug

---

contracts/Factory.sol
contracts/Pools.sol
contracts/Utils.sol

Reverts vetherasset/vaderprotocol-contracts#229

Revert "isSynth misc"

---

contracts/Synth.sol
contracts/Token2.sol
test/9_synths.js

Resolve Issue193 - synth decimals

---

contracts/DAO.sol
contracts/Router.sol
contracts/interfaces/iROUTER.sol
test/6_anchor.js

anchor replacement from DAO

---

contracts/DAO.sol
contracts/Router.sol
contracts/interfaces/iROUTER.sol
test/4_protection.js
test/5_rewards.js
test/6_anchor.js
test/7_dao.js
test/8_curation.js

Resolve Issue192: Replace Pools by DAO

---

contracts/DAO.sol
contracts/Vader.sol
contracts/interfaces/iVADER.sol
test/1_vader.js
test/4_protection.js
test/5_rewards.js
test/7_dao.js
test/91_lend.js
test/92_interest.js
test/9_synths.js

Closes #221 
* Emissions start by targetting an annual inflation rate (33%), then after 1 year, switch to a fixed daily emission. 
* Max supply 2bn
* DAO can control params

REsolve: Issue 221

---

contracts/DAO.sol
contracts/Router.sol
contracts/Vault.sol
test/7_dao.js

Resolve Issue24: Full DAO

---

contracts/Governance/GovernorAlpha.sol
contracts/Lender.sol
contracts/Router.sol
contracts/Utils.sol
contracts/Vader.sol
contracts/Vault.sol
contracts/interfaces/iVAULT.sol
test/1_vader.js
test/2_usdv.js
test/3_router.js
test/4_protection.js
test/5_rewards.js
test/6_anchor.js
test/7_curation.js
test/91_lend.js
test/92_interest.js
test/9_synths.js
test/GovernorAlpha/1_Propose.js
test/GovernorAlpha/2_CastVote.js
test/GovernorAlpha/3_Queue.js

Update test for merged Governor Alpha

update test for governor alpha

---

contracts/Lender.sol
contracts/Pools.sol
contracts/Router.sol
contracts/Vault.sol
contracts/interfaces/iPOOLS.sol
test/GovernorAlpha/3_Queue.js

Removed getAddedAmoun.
Updated test for GovernorAlpha Queue

remove getAddedAmount
